### ISSUE TITLE
The Man Who Found the Truth

### ISSUE THREAD

**Issue by michael-77** [robinwhittleton/leonid-andreyev_short-fiction_herman-bernstein_alexandra-linden_l-a-magnus_k-walter_w-h-lowe_the-rus#6]
I would think the reference to the Diary of a Prisoner should be in `<i>` rather than ""
The following `blockquote` should contain `epub:type="z3998:diary-entry"`
```
	<blockquote>
		<header>
			<p>
				<b>First lecture</b>
			</p>
		</header>
```
is cluncky - could we not just style it directly using just the `<header>` and `<p>` without the `<b>` in css?

**Comment by robinwhittleton** [comment]
The diary here is a fictional manuscript that is never published but burnt halfway through the story. I think that means that we should go with quotes instead of italics, but maybe @acabal has an opinion?

As for the header, this is fairly standard SE markup. I could change it, but then I’d have to scope the styles just to this story so I think it’s best left as is.

**Comment by acabal** [comment]
Which file are we referring to?

**Comment by michael-77** [comment]
The Man Who Found the Truth:
https://github.com/robinwhittleton/leonid-andreyev_short-fiction_herman-bernstein_alexandra-linden_l-a-magnus_k-walter_w-h-lowe_the-rus/blob/master/src/epub/text/the-man-who-found-the-truth.xhtml

**Comment by robinwhittleton** [comment]
For example, see the end of line 20: https://github.com/robinwhittleton/leonid-andreyev_short-fiction_herman-bernstein_alexandra-linden_l-a-magnus_k-walter_w-h-lowe_the-rus/blob/master/src/epub/text/the-man-who-found-the-truth.xhtml#L20

**Comment by acabal** [comment]
Yeah I would say it's not a "book" per se but more like a so-called manuscript, and I would assume on the shorter end anyway. Quotes are OK.

Re. styles, in general we add small-caps directly with a rule rather than adding b for headers. This one would be pretty simple, `#the-man-who-found-the-truth-9 blockquote header{ font-variant: small-caps; }`

**Comment by robinwhittleton** [comment]
OK, works for me. Fixed in https://github.com/robinwhittleton/leonid-andreyev_short-fiction_herman-bernstein_alexandra-linden_l-a-magnus_k-walter_w-h-lowe_the-rus/commit/f3c2e8bf88330a01cd8d0ad88f5399d64ef533d5.
